### ISSUE TITLE
Add websocket support in Perform

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-perform#13]
Add websockets real-time interaction using `graasp-query-client` and calling the corresponding hooks

**Comment by dialexo** [comment]
Will still have to update the `graasp-websockets` dependency once https://github.com/graasp/graasp-websockets/issues/15 is implemented

**Comment by dialexo** [comment]
Issue with converting to new API (https://github.com/graasp/graasp-query-client/pull/50):

- calls the `useChildren` hook with `enabled` set to `isFolder`. In the current implementation, it will fetch ws updates even if `isFolder` set to false, unless `getUpdates: false` is specified. The same issue probably happens with `graasp-ui` dependency (`DynamicTreeView` receives `useChildren` as prop). Fix: disable websockets if `enable: false`.

- Can't upgrade packages (query-client) to latest master with new API:
```
Internal Error: @graasp/query-client@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Mk.getCandidates (/home/dialexo/.cache/yarn/v6/.tmp/b72194be45e282fbe4c95ef53d1e4ec6.5cd8e1392d81583d754baaa9371157400543b77e.prepare/.yarn/releases/yarn-3.0.1-rc.1.cjs:299:4306)
    at Xc.getCandidates (/home/dialexo/.cache/yarn/v6/.tmp/b72194be45e282fbe4c95ef53d1e4ec6.5cd8e1392d81583d754baaa9371157400543b77e.prepare/.yarn/releases/yarn-3.0.1-rc.1.cjs:294:4947)
    at /home/dialexo/.cache/yarn/v6/.tmp/b72194be45e282fbe4c95ef53d1e4ec6.5cd8e1392d81583d754baaa9371157400543b77e.prepare/.yarn/releases/yarn-3.0.1-rc.1.cjs:303:7643
    at Gl (/home/dialexo/.cache/yarn/v6/.tmp/b72194be45e282fbe4c95ef53d1e4ec6.5cd8e1392d81583d754baaa9371157400543b77e.prepare/.yarn/releases/yarn-3.0.1-rc.1.cjs:242:4003)
    at y (/home/dialexo/.cache/yarn/v6/.tmp/b72194be45e282fbe4c95ef53d1e4ec6.5cd8e1392d81583d754baaa9371157400543b77e.prepare/.yarn/releases/yarn-3.0.1-rc.1.cjs:303:7623)
error Command failed with exit code 1.
```
